### ISSUE TITLE
[BUG] Exchange name displayed over two lines isn't crossed when user clicks on it

### ISSUE THREAD

**Issue by adeacetis** [Tucsky/aggr#338]
### Describe the issue

As a user, I can disable an exchange by clicking on the exchange name in the global settings pane > section exchanges.

If the name appears on two lines, the animated strike-through is located in the middle instead of over the name.

![image](https://github.com/Tucsky/aggr/assets/20586054/34b4375f-0698-407f-9987-5c91007b05c2)

### Steps to reproduce

1. Click on the bottom right green circle button to open the global setting pane.
2. Scroll to the exchange settings.
3. Click on Binance Futures US

### To-do 
- [ ] I added my [browser's console](https://balsamiq.com/support/faqs/browserconsole/) output in the issue (open the console first, try to reproduce the issue then see if there is anything)
NA
- [ ] I have attached [an export of my aggr database](https://imgur.com/a/traIrKb) in the issue
NA
- [x] I documented the issue with screenshots
- [x] I provided a clear and concise description of what the bug is (see both sections below)

**Comment by adeacetis** [comment]
Given the recent trouble Binance and Binance Futures are going through. This issue is clearly not a top priority.
